import { assessProfessionalDraft, assertProfessionalExportReady } from "./professionalDraft";
import { adaptDemoCaseToFieldStudy } from "@/lib/storage/demoStudyAdapter";
import type { DemoCase, FieldStudy } from "@/lib/types";
import {
  isFindingExportEligible,
  isRecommendationExportEligible,
  isLessonExportEligible,
  isGoodPracticeExportEligible,
  getLinkedFindingIds,
  type CanonicalExportContext,
} from "./exportPolicy";

export interface ExportFinding {
  id: string;
  statement: string;
  explanation: string;
  evidenceBase: string[];
  programmeImplication: string;
  limitationNote?: string;
  alternativeInterpretations?: string;
  contradictoryEvidenceIds: string[];
  qualifyingEvidenceIds: string[];
}

export interface ExportLesson {
  id: string;
  statement: string;
  linkedFindingIds?: string[];
  whatWorkedOrDidNotWork: string;
  whyItHappened: string;
  conditionsRequired: string;
  evidenceBase: string[];
  transferability: string;
}

export interface ExportGoodPractice {
  id: string;
  title: string;
  linkedFindingIds?: string[];
  description: string;
  whyItWorked: string;
  evidenceBase: string[];
  conditionsForReplication: string;
  risksLimits: string;
  recommendedUse: string;
}

export interface ExportRecommendation {
  id: string;
  recommendation: string;
  linkedFindingId: string;
  linkedFindingIds: string[];
  evidenceBase: string[];
  responsibleActor: string;
  priority: string;
  timeframe: string;
  feasibility: string;
  riskSensitivity: string;
  expectedBenefit: string;
  successIndicator: string;
}

export interface ExportTraceItem {
  findingId: string;
  evidenceIds: string[];
  recommendationIds: string[];
}

export interface ExportSandboxEvidence {
  id: string;
  sourceId: string;
  stakeholderType: string;
  rawEvidence: string;
  primaryTheme: string;
  sensitivityFlag: string;
  draftFindingId?: string;
  draftFindingStatement?: string;
  draftRecommendationId?: string;
  draftRecommendationStatement?: string;
}

export interface BriefExportModel {
  caseId: string;
  title: string;
  subtitle: string;
  executiveSummary: string;
  keyMessages: string[];
  purposeAndScope?: string;
  keyThemes?: string[];
  findings: ExportFinding[];
  lessons: ExportLesson[];
  goodPractices: ExportGoodPractice[];
  recommendations: ExportRecommendation[];
  safeguardingNotes?: string;
  limitations: string[];
  traceability: ExportTraceItem[];
  safetyNote: string;
  demoNote: string;
  reviewNote: string;
  generatedDate: string;
  includeSandbox?: boolean;
  sandboxEvidence?: ExportSandboxEvidence[];
}

export function buildBriefExportModel(
  demoCase: DemoCase | FieldStudy,
  includeSandbox: boolean = false,
  options: { fileAvailability?: Record<string, boolean>; professionalExport?: boolean } = {}
): BriefExportModel {
  if (demoCase.isDemoCase === true && "project" in demoCase) {
    const normalized = adaptDemoCaseToFieldStudy(demoCase);
    demoCase = { ...demoCase, sources: normalized.sources, evidence: normalized.evidence, findings: normalized.findings, lessons: normalized.lessons, goodPractices: normalized.goodPractices, recommendations: normalized.recommendations };
  }
  const draft = demoCase.professionalDraft;
  const draftReview = draft ? assessProfessionalDraft(demoCase, draft, options.fileAvailability) : undefined;
  if (options.professionalExport && includeSandbox) throw new Error("Sandbox drafts cannot be included in professional export.");
  if (options.professionalExport) assertProfessionalExportReady(demoCase, options.fileAvailability);
  const executiveSummary = draft ? draft.manualExecutiveSummary : demoCase.executiveSummary;
  const keyMessages = draft ? draft.manualKeyMessages : demoCase.keyMessages;
  const selected = (kind: "findings" | "lessons" | "goodPractices" | "recommendations", id: string) => !draftReview ||
    (kind === "findings" ? draftReview.findingIds.has(id) : draftReview.validItems.some(item => item.kind === kind && item.recordId === id));
  const isLegacyDemo = demoCase.isDemoCase === true;
  const safetyNote = isLegacyDemo ? (("safetyNote" in demoCase ? demoCase.safetyNote : undefined) || (demoCase.id === "school-nutrition" ? "This case is a sanitized demo derived from prior fieldwork. No raw identifiable field data is included." : "This case uses fictional demo data for product validation.")) : "Browser-local study draft. Review confidentiality and participant consent before sharing.";
  const demoNote = isLegacyDemo ? (demoCase.id === "school-nutrition" ? "Sanitized real-world-inspired demo context; seeded review metadata is illustrative." : "Fictional demo context; seeded review metadata is illustrative.") : "Practitioner study context.";
  const hasUnlinkedText = Boolean(executiveSummary?.trim() || keyMessages?.some(text => text.trim()));
  let reviewNote = "Professional draft generated by Field Learning Studio. Human review required before external use." + (hasUnlinkedText ? " UNLINKED SUBSTANTIVE FREE TEXT: executive summary and key messages have no structured claim-level lineage; their grounding has not been checked." : "");
  if (draftReview) reviewNote += ` ${options.professionalExport ? "READY FOR PROFESSIONAL EXPORT: deterministic integrity conditions checked; human sign-off remains required." : "WORKING DRAFT."} Structured records are intentionally selected; parent Findings are included as linked analytical context.` +
    (draftReview.blockers.length ? ` NEEDS ATTENTION: ${draftReview.blockers.join("; ")}. Non-current or changed selections are excluded from this output; inclusion snapshots remain in the workspace.` : "") +
    (draftReview.fileState === "UNAVAILABLE" ? " UNAVAILABLE: no original files referenced by the selected material; source records remain linked." : "");
  const currentDate = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

  const context: CanonicalExportContext = {
    sources: demoCase.sources,
    evidence: demoCase.evidence,
    findings: demoCase.findings,
    isLegacyDemo,
  };

  const filteredFindings = demoCase.findings.filter((f) =>
    isFindingExportEligible(f, context) && selected("findings", f.id)
  );

  const filteredRecs = demoCase.recommendations.filter((r) =>
    isRecommendationExportEligible(r, context) && selected("recommendations", r.id)
  );

  const filteredLessons = demoCase.lessons.filter((l) =>
    isLessonExportEligible(l, context) && selected("lessons", l.id)
  );

  const filteredGoodPractices = demoCase.goodPractices.filter((g) =>
    isGoodPracticeExportEligible(g, context) && selected("goodPractices", g.id)
  );

  const sandboxEvidence: ExportSandboxEvidence[] = [];
  if (includeSandbox) {
    demoCase.evidence
      .filter((e) => e.id.includes("SBX") || e.id.includes("TEMP"))
      .forEach((e) => {
        const fnd = demoCase.findings.find((f) => f.supportingEvidenceIds.includes(e.id));
        const rec = fnd ? demoCase.recommendations.find((r) => r.linkedFindingId === fnd.id) : null;
        sandboxEvidence.push({
          id: e.id,
          sourceId: e.sourceId,
          stakeholderType: e.stakeholderType,
          rawEvidence: e.rawEvidence,
          primaryTheme: e.primaryTheme,
          sensitivityFlag: e.sensitivityFlag,
          draftFindingId: fnd?.id,
          draftFindingStatement: fnd?.statement,
          draftRecommendationId: rec?.id,
          draftRecommendationStatement: rec?.recommendation,
        });
      });
  }

  const projectTitle = "project" in demoCase ? demoCase.project : demoCase.title;

  return {
    caseId: demoCase.id,
    title: `${projectTitle}: Learning Brief`,
    subtitle: demoCase.subtitle,
    executiveSummary,
    keyMessages,
    purposeAndScope: "purposeAndScope" in demoCase ? demoCase.purposeAndScope : undefined,
    keyThemes: "keyThemes" in demoCase ? demoCase.keyThemes : undefined,
    findings: filteredFindings.map((f) => ({
      id: f.id,
      statement: f.statement,
      explanation: [f.explanation,
        f.limitationNote?.trim() ? `Limitations: ${f.limitationNote.trim()}` : "",
        f.alternativeInterpretations?.trim() ? `Alternative interpretations: ${f.alternativeInterpretations.trim()}` : "",
        f.contradictoryEvidence?.trim() && !/^(none|n\/a|no contradictions)( documented| noted)?\.?$/i.test(f.contradictoryEvidence.trim()) ? `Recorded challenge: ${f.contradictoryEvidence.trim()}` : "",
        ...(f.contradictoryEvidenceIds || []).map(id => `Challenging observation (${id}): ${demoCase.evidence.find(e => e.id === id)?.rawObservation || demoCase.evidence.find(e => e.id === id)?.rawEvidence || ""}`),
        ...(f.qualifyingEvidenceIds || []).map(id => `Qualifying context (${id}): ${demoCase.evidence.find(e => e.id === id)?.rawObservation || demoCase.evidence.find(e => e.id === id)?.rawEvidence || ""}`),
      ].filter(Boolean).join("\n\n"),
      limitationNote: f.limitationNote,
      alternativeInterpretations: f.alternativeInterpretations,
      contradictoryEvidenceIds: f.contradictoryEvidenceIds || [],
      qualifyingEvidenceIds: f.qualifyingEvidenceIds || [],
      evidenceBase: f.supportingEvidenceIds,
      programmeImplication: f.programmeImplication,
    })),
    lessons: filteredLessons.map((l) => ({
      id: l.id,
      statement: l.statement,
      linkedFindingIds: getLinkedFindingIds(l),
      whatWorkedOrDidNotWork: l.whatWorkedOrDidNotWork,
      whyItHappened: l.whyItHappened,
      conditionsRequired: l.conditionsRequired,
      evidenceBase: l.evidenceBase,
      transferability: l.transferability,
    })),
    goodPractices: filteredGoodPractices.map((g) => ({
      id: g.id,
      title: g.title,
      linkedFindingIds: getLinkedFindingIds(g),
      description: g.description,
      whyItWorked: g.whyItWorked,
      evidenceBase: g.evidenceBase,
      conditionsForReplication: g.conditionsForReplication,
      risksLimits: g.risksLimits,
      recommendedUse: g.recommendedUse,
    })),
    recommendations: filteredRecs.map((r) => ({
      id: r.id,
      recommendation: r.recommendation,
      linkedFindingId: r.linkedFindingId,
      linkedFindingIds: getLinkedFindingIds(r),
      evidenceBase: r.evidenceBase,
      responsibleActor: r.responsibleActor,
      priority: r.priority || "Not recorded",
      timeframe: r.timeframe,
      feasibility: r.feasibility,
      riskSensitivity: r.riskSensitivity,
      expectedBenefit: r.expectedBenefit,
      successIndicator: r.successIndicator,
    })),
    safeguardingNotes: "safeguardingNotes" in demoCase ? demoCase.safeguardingNotes : undefined,
    limitations: demoCase.limitations,
    traceability: filteredFindings.map((f) => ({
      findingId: f.id,
      evidenceIds: [...f.supportingEvidenceIds, ...(f.contradictoryEvidenceIds || []), ...(f.qualifyingEvidenceIds || [])],
      recommendationIds: filteredRecs.filter(r => getLinkedFindingIds(r).includes(f.id)).map(r => r.id),
    })),
    safetyNote,
    demoNote,
    reviewNote,
    generatedDate: currentDate,
    includeSandbox,
    sandboxEvidence: sandboxEvidence.length > 0 ? sandboxEvidence : undefined,
  };
}
